### ISSUE TITLE
Improve temporary file handling

### ISSUE THREAD

**Issue by qubit05** [phlib/flysystem-pdo#3]
At the moment the files are stored in temporary filesystem files which are left behind. It would be better to use the php://temp

> php://temp will use a temporary file once the amount of data stored hits a predefined limit (the default is 2 MB). The location of this temporary file is determined in the same way as the sys_get_temp_dir() function.

**Comment by glensc** [comment]
i was migrating large amounts of data from one adapter to another, and got hit by this problem. leaving hundreds of megabytes of temp files to `$TMPDIR`.

**Comment by qubit05** [comment]
Hi @glensc 

Sorry for the delay in getting this sorted. Version 1.1 has now been released. Hope this fixes the problem for you.

**Comment by glensc** [comment]
yes. thanks. it did fix. will update to use actual tag now.
